# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nutr_type.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Nutr(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 550)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 501, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_33.setObjectName("label_33")
        self.verticalLayout.addWidget(self.label_33)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_rast = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_rast.setObjectName("rb_rast")
        self.horizontalLayout.addWidget(self.rb_rast)
        self.rb_nasek = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_nasek.setObjectName("rb_nasek")
        self.horizontalLayout.addWidget(self.rb_nasek)
        self.rb_hish = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_hish.setObjectName("rb_hish")
        self.horizontalLayout.addWidget(self.rb_hish)
        self.rb_vse = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_vse.setObjectName("rb_vse")
        self.horizontalLayout.addWidget(self.rb_vse)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pb_ans = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_ans.setObjectName("pb_ans")
        self.horizontalLayout.addWidget(self.pb_ans)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_33.setText(_translate("Form", "К какой группе по типу питания относится это животное?"))
        self.rb_rast.setText(_translate("Form", "Растительноядные"))
        self.rb_nasek.setText(_translate("Form", "Насекомоядные"))
        self.rb_hish.setText(_translate("Form", "Хищники"))
        self.rb_vse.setText(_translate("Form", "Всеядные"))
        self.pb_ans.setText(_translate("Form", "Ответить"))
        self.label_2.setText(_translate("Form", "Баллы"))
