# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vow_con.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Vow_Con(object):
    def setupUi(self, Form):
        Form.setObjectName("Гласные и согласные буквы")
        Form.resize(270, 181)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.let_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.let_btn.setText("")
        self.let_btn.setObjectName("let_btn")
        self.horizontalLayout.addWidget(self.let_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb_glas = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_glas.setObjectName("rb_glas")
        self.horizontalLayout_2.addWidget(self.rb_glas)
        self.rb_sogl = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_sogl.setObjectName("rb_sogl")
        self.horizontalLayout_2.addWidget(self.rb_sogl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ans_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ans_btn.setObjectName("ans_btn")
        self.horizontalLayout_3.addWidget(self.ans_btn)
        self.balls_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.balls_btn.setObjectName("balls_btn")
        self.horizontalLayout_3.addWidget(self.balls_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Гласные и согласные"))
        self.rb_glas.setText(_translate("Form", "Гласная"))
        self.rb_sogl.setText(_translate("Form", "Согласная"))
        self.ans_btn.setText(_translate("Form", "Готово"))
        self.balls_btn.setText(_translate("Form", "0"))
